CREATE TABLE capsules(
 id BIGSERIAL NOT NULL,
 capsuleName VARCHAR(100) NOT NULL,
 capsuleDesc VARCHAR(500) NOT NULL,
 creatorName VARCHAR(100),
 capsuleType VARCHAR(100) NOT NULL,
 date VARCHAR(100) NOT NULL,
 time VARCHAR(100) NOT NULL
);